// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallRecord struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=StartTime" json:"StartTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=EndTime" json:"EndTime,omitempty"`
	Duration             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Duration" json:"Duration,omitempty"`
	CallerLineIdentity   string               `protobuf:"bytes,5,opt,name=callerLineIdentity" json:"callerLineIdentity,omitempty"`
	NonChargedParty      string               `protobuf:"bytes,6,opt,name=NonChargedParty" json:"NonChargedParty,omitempty"`
	CallRecords          []*CallRecord        `protobuf:"bytes,7,rep,name=CallRecords" json:"CallRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CallRecord) Reset()         { *m = CallRecord{} }
func (m *CallRecord) String() string { return proto.CompactTextString(m) }
func (*CallRecord) ProtoMessage()    {}
func (*CallRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_54c3f75bfe5b8a53, []int{0}
}
func (m *CallRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRecord.Unmarshal(m, b)
}
func (m *CallRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRecord.Marshal(b, m, deterministic)
}
func (dst *CallRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRecord.Merge(dst, src)
}
func (m *CallRecord) XXX_Size() int {
	return xxx_messageInfo_CallRecord.Size(m)
}
func (m *CallRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CallRecord proto.InternalMessageInfo

func (m *CallRecord) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CallRecord) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *CallRecord) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *CallRecord) GetDuration() *timestamp.Timestamp {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *CallRecord) GetCallerLineIdentity() string {
	if m != nil {
		return m.CallerLineIdentity
	}
	return ""
}

func (m *CallRecord) GetNonChargedParty() string {
	if m != nil {
		return m.NonChargedParty
	}
	return ""
}

func (m *CallRecord) GetCallRecords() []*CallRecord {
	if m != nil {
		return m.CallRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*CallRecord)(nil), "model.CallRecord")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_model_54c3f75bfe5b8a53) }

var fileDescriptor_model_54c3f75bfe5b8a53 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x6a, 0x5a, 0x3b, 0x01, 0xc5, 0x39, 0x2d, 0xbd, 0x18, 0x3c, 0xe5, 0xb4, 0x85,
	0x56, 0xc4, 0x7b, 0xf5, 0x20, 0x88, 0xc8, 0xda, 0x3f, 0xb0, 0xed, 0x8e, 0x71, 0x61, 0xb3, 0x5b,
	0xb6, 0xd3, 0x43, 0x7f, 0xa7, 0x7f, 0x48, 0xd8, 0x10, 0x23, 0x52, 0xe8, 0x71, 0xde, 0xfb, 0xde,
	0x63, 0x78, 0x50, 0xb6, 0xc1, 0x90, 0x93, 0xbb, 0x18, 0x38, 0x60, 0x91, 0x8e, 0xd9, 0x6d, 0x13,
	0x42, 0xe3, 0x68, 0x9e, 0xc4, 0xcd, 0xe1, 0x73, 0xce, 0xb6, 0xa5, 0x3d, 0xeb, 0x76, 0xd7, 0x71,
	0x77, 0xdf, 0x39, 0xc0, 0x4a, 0x3b, 0xa7, 0x68, 0x1b, 0xa2, 0xc1, 0x2b, 0xc8, 0xad, 0x11, 0x59,
	0x95, 0xd5, 0x85, 0xca, 0xad, 0xc1, 0x47, 0x98, 0x7e, 0xb0, 0x8e, 0xbc, 0xb6, 0x2d, 0x89, 0xbc,
	0xca, 0xea, 0x72, 0x31, 0x93, 0x5d, 0xa7, 0xec, 0x3b, 0xe5, 0xba, 0xef, 0x54, 0x03, 0x8c, 0xf7,
	0x30, 0x79, 0xf6, 0x26, 0xe5, 0x46, 0x67, 0x73, 0x3d, 0x8a, 0x0f, 0x70, 0xf9, 0x74, 0x88, 0x9a,
	0x6d, 0xf0, 0xe2, 0xe2, 0x6c, 0xec, 0x97, 0x45, 0x09, 0xb8, 0xd5, 0xce, 0x51, 0x7c, 0xb5, 0x9e,
	0x5e, 0x0c, 0x79, 0xb6, 0x7c, 0x14, 0x45, 0x95, 0xd5, 0x53, 0x75, 0xc2, 0xc1, 0x1a, 0xae, 0xdf,
	0x82, 0x5f, 0x7d, 0xe9, 0xd8, 0x90, 0x79, 0xd7, 0x91, 0x8f, 0x62, 0x9c, 0xe0, 0xff, 0x32, 0x2e,
	0xa1, 0x1c, 0xf6, 0xd9, 0x8b, 0x49, 0x35, 0xaa, 0xcb, 0xc5, 0x8d, 0xec, 0xb6, 0x1e, 0x1c, 0xf5,
	0x97, 0xda, 0x8c, 0xd3, 0xb3, 0xcb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0xaf, 0xe8, 0xf3,
	0x93, 0x01, 0x00, 0x00,
}
